### PR TITLE
feat: make NamingService and ConfigService Send + Sync

### LINKED ISSUE #227: ConfigService is not Send + Sync
https://github.com/nacos-group/nacos-sdk-rust/blob/207421aad7bbf0f0f0e7945b9b94bd91977028b5/src/api/config.rs#L22C11-L22C24

Better changed to 

```rust
pub trait ConfigService: Send + Sync {
//...
}
```

So that `ConfigService` can be async friendlier.

### PR DESCRIPTION
**Pull request by thynson**
Resolves #227

### CODE REVIEW

**Comment by onewe** [comment]
LGTM

**Review by CherishCai — APPROVED** [review]
LGTM

**Comment by thynson** [comment]
I just realized that it's could a breaking change. If shipped,  existing implementations of these traits may failed to compile due to not being `Send + Sync`.
Given that nacos-sdk-rust is still in `0.x` era, I would like to suggest to bump to `0.4.x` for next release.

**Comment by CherishCai** [comment]
> I just realized that it's could a breaking change. If shipped, existing implementations of these traits may failed to compile due to not being `Send + Sync`. Given that nacos-sdk-rust is still in `0.x` era, I would like to suggest to bump to `0.4.x` for next release.

有道理，main 应用应该没问题，若是 lib 库依赖是否有问题。那么原生 async 也考虑 0.4 搞起来

**Pull request merged**
